environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"
cache:
  - '%LOCALAPPDATA%\pip\Cache'
install:
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "git clone https://github.com/Drakkar-Software/OctoBot %APPVEYOR_BUILD_FOLDER%\\OctoBot"
  - cd OctoBot
  - "%PYTHON%\\python.exe -m pip install -r pre_requirements.txt"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt -r dev_requirements.txt"
  - copy config\default_config.json config.json
  - "%PYTHON%\\python.exe start.py -p install all"
build_script:
  - "mkdir %APPVEYOR_BUILD_FOLDER%\\OctoBot\\bin"
  - "copy %APPVEYOR_BUILD_FOLDER%\\bin\\start.spec %APPVEYOR_BUILD_FOLDER%\\OctoBot\\bin\\start.spec"
  - "%PYTHON%\\python.exe -m nltk.downloader -d %NLTK_DATA% words"
  - "%PYTHON%\\Scripts\\pyinstaller.exe %APPVEYOR_BUILD_FOLDER%\\OctoBot\\bin\\start.spec"
  - "echo f | xcopy /f /y dist\\OctoBot.exe dist\\OctoBot_windows.exe"
  - "powershell get-filehash -algorithm sha1 dist\\OctoBot_windows.exe"
artifacts:
  - path: OctoBot/dist/OctoBot_windows.exe
    name: OctoBot_windows.exe
deploy:
  - provider: Environment
    name: GITHUB_RELEASE_OCTOBOT_BINARY
    draft: false
    prerelease: false
    artifact: OctoBot_windows.exe
    on:
      APPVEYOR_REPO_TAG: true
